name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 2.0.9+9

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^8.0.0
  provider: ^6.0.3
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  http: ^1.2.2
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.0.2
  image_picker: ^1.1.2
  webview_flutter: ^4.9.0
  flutter_html: ^3.0.0-alpha.3
  share_plus: ^10.0.3
  photo_view: ^0.15.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.0.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  flutter_svg: ^2.0.10+1
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.2.5
  flutter_google_places_hoc081098: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  flutter_typeahead: ^5.2.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.15.2
  flutter_widget_from_html_core: ^0.15.2
  flutter_html_table: ^3.0.0-alpha.3
  fluttertoast: ^8.0.9
  permission_handler: ^11.3.1
  flutter_downloader: ^1.8.0+1
  country_currency_pickers: ^3.0.0
  dropdown_search: ^6.0.1
  flutter_inappwebview: ^6.1.5
  path: ^1.8.2
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  intl: any
  flutter_google_maps_webservices: ^1.1.1
  sign_in_with_apple: ^6.1.3
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.1.1
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  flutter_native_splash: ^2.3.2
  animations: ^2.0.8
  emoji_picker_flutter: ^3.1.0
  flutter_otp_text_field: ^1.2.0
  webview_flutter_android: ^3.16.9
  webview_flutter_wkwebview: ^3.16.0





  collection: any
  group_radio_button: ^1.3.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1   

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
